#pragma once
#define RT_SUCCESS_TWOHWC_ANGLE		7						//载入出厂位移校准数据、二次位移校准数据、光谱入射角成功。
#define RT_SUCCESS_HWC_ANGLE		5						//载入出厂位移校准数据和光谱入射角成功。
#define RT_NOTHING					4						//未进行任何任何操作
#define RT_SUCCESS_TWOHWC			3						//载入出厂位移校准数据和二次位移校准数据成功。
#define RT_SUCCESS_STOPCAPTURE		2						//主动停止采集任务成功。
#define RT_SUCCESS					1						//成功。
#define RT_WAITING_DEVICESTATUS		0						//控制器已完成上一次采集任务或无采集任务，等待开启采集任务指令。
#define RT_DEVICEGETTING			-1						//指定控制器正在采集数据中，操作失败。
#define RT_NOTFINDDEVICE			-2						//未找到指定序列号控制器。
#define RT_ERROR_OPENCLOSEDEVICE	-3						//打开或关闭控制器异常，请先断电重启控制器，然后重启软件。
#define RT_ILLEGALLY				-4						//指定序列号控制器类型非法，非本公司设备。
#define RT_DEVICE_OPENED			-5						//指定控制器已打开。
#define RT_MAX_DEVICEOPENED			-6						//当前已打开控制器达到最大数量，无法再打开新控制器。
#define RT_DEVICENOTOPEN			-7						//控制器未打开，无法获取数据。
#define RT_OPEN_TIMEOUT				-8						//控制器打开超时，请先断电重启控制器，然后重启软件。
#define RT_ERROR_GETDATA			-9						//控制器打开正常，开始采集数据异常。
#define RT_FAILED_INITDLL			-10						//未成功初始化传感器DLL。
#define RT_FAILED_GETORSETPARAM		-11						//设置参数或获取参数失败，需断电重启控制器。
#define RT_INVALID_PARAM			-12						//给定参数非法。
#define RT_ERROR_CALCDARKPARAM		-13						//计算Dark条件失败。
#define RT_INVALID_CHANNEL			-14						//指定通道不存在或未启用。
#define RT_CLOSE_TIMEOUT			-15						//控制器关闭超时，请断电重启控制器。
#define RT_NOTSUPPORT_FUNCATION		-16						//指定功能不支持。
#define RT_ERROR_SPECTRUMCENTER		-17						//光谱中心位置异常，dark失败。
#define RT_DARK_PARAMSETFAILED		-18						//dark时参数设置异常,Dark操作将异常结束。
#define RT_PEAKS_NOTENOUGH			-19						//用于厚度校准的2个波峰强度太弱，校准失败，请调节样品的位置或适当的加强增益曝光，以达到能进行厚度校准的条件。
#define RT_DARK_DONOTWORK			-20						//控制器未进行Dark，无法获取比例。
#define RT_TIMEOUT_GETORSETPARAM	-23						//控制器设置、获取参数超时，请重试。
#define RT_TIMEOUT_GETDATA			-24						//数据采集超时。
#define RT_USERSTOP_DARK			-25						//dark操作被强行停止。
#define RT_TIMEOUT_STOPCAPTURE		-26						//主动停止采集任务超时，请重试。
#define RT_SELECTDCTYPE_ERROR		-27						//DLL已完成初始化无法再修改控制器类型或再次初始化DLL，请先进行反初始化DLL再执行修改控制器类型或初始化DLL操作。
#define RT_FAILED_SETTRIGGERSOURCE	-28						//设置触发信号源失败，请断电重启控制器。
#define RT_INVALID_DOG				-29						//未找到匹配的加密狗。
#define RT_FAILED_INITUSB1			-30						//USB一代控制器初始化失败，请检查是否已安装USB一代最新版驱动。
#define RT_FAILED_INITETHERNET		-31						//以太网控制器初始化失败，请检查是否已安装以太网版本驱动。
#define RT_FAILED_INITUSB2			-32						//USB二代控制器初始化失败，请检查是否已安装USB二代最新版驱动。
#define RT_FAILED_CAPTURERSCDATA	-33						//控制器采集原始数据异常，请断电重启控制器。
#define RT_FAILED_FREEMEMORY		-34						//控制器释放采集数据内存异常，请断电重启控制器。
#define RT_FAILED_CLOSEDOG			-35						//加密狗关闭异常，请关闭软件后拔插解密狗，然后重启软件。
#define RT_INVALID_HANDLE			-36						//给定设备句柄无效。
#define RT_CONNECTERROR_DEVICE		-37						//设备连接异常，USB接口类型控制器有可能是USB接口电压不稳，以太网接口类型控制器有可能是数据线连接不稳或千兆网口性能欠佳。
#define RT_ERROR_UNINITDLL			-38						//DLL反初始化异常，请将控制器断电重启后再试。
#define RT_MISMATCH_FILETYPE		-100					//文件类型不匹配。
#define RT_NOTFIND_CHANNELDATA		-101					//在指定文件中未找到与指定序列号控制器及通道匹配的数据。
#define RT_FAILED_OPENFILE			-102					//文件访问失败，请检查该文件是否被占用。
#define RT_FILE_INEXISTENCE			-103					//给定路径文件不存在。
#define RT_ERROR_LOADDATAFROMFILE	-104					//加载文件发现异常，请重启软件。
#define RT_ERROR_SAVEPARAM			-105					//保存配置到文件失败。
#define RT_ERROR_NOPARAMTOSAVE		-106					//无有效控制器配置数据可保存。
#define RT_OVER_DARKCOUNT			-107					//Dark参数组数量异常请重新Dark。
#define RT_FAILED_LOADDARK			-108					//从文件载入Dark数据失败，请执行Dark操作。
#define RT_FAILED_MATCHDARK			-109					//当前参数无匹配Dark数据，请确保当前使用增益为0或2的倍数。
#define RT_MISMATCH_MATERIAL		-112					//无匹配的材质校准数据。
#define RT_OVER_MATERIALCOUNT		-113					//给定文件材质库数量超出限制，最多500种。
#define RT_OVER_FILELENGTH			-114					//文件路径长度超过最大限制，目前最大限制长度为2000个字符。
#define RT_FILE_INVALIDLOAD			-115					//保存修改后的控制器参数前，未成功载入通道有效参数，无法保存，如需保存需至少成功载入一次控制器参数。
#define RT_CALIBRATION_NOTLOAD		-116					//未载入控制器出厂校准数据，无法进行二次位移校准数据计算或保存。
#define RT_INVALID_RSCDATA			-117					//给定二次校准数组非法，请检查给定数据有效性。
#define RT_FAILED_SAVEDISTANCE2		-118					//保存位移二次校准数据失败，请确认hwc文件未被其他程序占用。
#define RT_INVALID_DISTANCE2VALUE	-119					//二次校准结果值与出厂校准数据偏离超过最大比例，二次校准值无效。
#define RT_NOTEXIST_DISTANCE2		-120					//二次校准数据不存在，无法获取或选择使用。
#define RT_ERROR_SAVEDARKDATA		-121					//Dark数据存档失败，请检查控制器配置文件是否被删除。
#define RT_ERROR_DLLPATH			-122					//DLL路径获取异常，请缩短当前程序路径长度或更换程序文件到其他路径重试。 20200112
#define RT_ERROR_WORKMODE			-123					//工作模式错误

#define RT_MODE_ERROR_SET_PARAM		-124					//该参数关联模式错误，无法设置该参数，需要先修改为正确的模式才能设置该参数。
#define RT_ERROR_CREATE_THREAD		-125					//DLL内部开启线程失败。

#define RT_GAUSSFILTERTHREEFACTORY_ERROR -260				//滤波功能异常，请检查相关参数设置是否合法。
#define RT_EXTREMEDATAPROCESS_ERROR -261					//去极值功能异常，请检查相关参数设置是否合法。
#define RT_LOW_USERGRADE			-262					//用户等级太低，此函数拒绝执行。
//20220622增加
#define RT_CMC_INITNET				-300					//加载套接字库失败
#define RT_CMC_CREATE_SOCKET		-301					//创建套接字库失败
#define RT_CMC_BIND					-302					//绑定套接字出错
#define RT_CMC_LISTEN				-303					//监听出错
#define RT_CMC_ACCEPT				-304					//接收客户端请求出错
#define RT_CMC_SERVERCLOSE			-305					//控制器服务端已关闭，无法读取数据
#define RT_CMC_WRITEFAILED			-306					//数据写入失败
#define RT_CMC_READFAILED			-307					//读取数据失败
#define RT_CMC_CLOSE				-308					//关闭出错
#define RT_CMC_CONNECT				-309					//连接控制器服务端出错
#define RT_CMC_OPENFAILED			-310					//打开客户端失败
#define RT_CMC_TIMEOUT_LOGIN		-311					//登陆用户超时
#define RT_CMC_TIMEOUT_CLEAR		-312					//清空接收缓冲区失败
#define RT_CMC_ERROR_READ_BUFFERDATA	-313				//读取缓冲区数据异常，实际读取到的数据数量小于数据包头部标注的数量。
#define RT_FAILED_INITEBD			-400					//嵌入式控制器初始化失败，请检查是否缺少必要DLL文件。

